# Laboratorio 2: Armado de un esquema de aprendizaje automático

En el laboratorio final se espera que puedan poner en práctica los conocimientos adquiridos en el curso, trabajando con un conjunto de datos de clasificación.

El objetivo es que se introduzcan en el desarrollo de un esquema para hacer tareas de aprendizaje automático: selección de un modelo, ajuste de hiperparámetros y evaluación.

El conjunto de datos a utilizar está en `./data/loan_data.csv`. Si abren el archivo verán que al principio (las líneas que empiezan con `#`) describen el conjunto de datos y sus atributos (incluyendo el atributo de etiqueta o clase).

Se espera que hagan uso de las herramientas vistas en el curso. Se espera que hagan uso especialmente de las herramientas brindadas por `scikit-learn`.

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import itertools
from sklearn.metrics import confusion_matrix

%matplotlib inline

# TODO: Agregar las librerías que hagan falta

np.random.seed(0)  # Para mayor determinismo

## Carga de datos

La celda siguiente se encarga de la carga de datos (haciendo uso de pandas). Estos serán los que se trabajarán en el resto del laboratorio.

In [3]:
dataset = pd.read_csv("./data/loan_data.csv", comment="#")
display(dataset.head(20))

# División entre instancias y etiquetas
X, y = dataset.iloc[:, 1:], dataset.TARGET

TARGET   LOAN   MORTDUE     VALUE   YOJ  DEROG  DELINQ       CLAGE  NINQ  \
0        0   4700   88026.0  115506.0   6.0    0.0     0.0  182.248332   0.0   
1        0  19300   39926.0  101208.0   4.0    0.0     0.0  140.051638   0.0   
2        0   5700   71556.0   79538.0   2.0    0.0     0.0   92.643085   0.0   
3        0  13000   44875.0   57713.0   0.0    1.0     0.0  184.990324   1.0   
4        0  19300   72752.0  106084.0  11.0    0.0     0.0  193.707100   1.0   
5        0  11500   53651.0   87547.0  18.0    0.0     0.0  191.396887   0.0   
6        0  17200  103519.0  118074.0   0.0    0.0     0.0  102.678612   1.0   
7        0  24200   22763.0   47622.0  23.0    0.0     0.0  126.922691   1.0   
8        0  12600   62493.0   77141.0  13.0    0.0     0.0  266.333101   0.0   
9        0  12300   90006.0  121122.0   9.0    0.0     0.0  133.497541   1.0   
10       0  35100   88197.0  132776.0  30.0    0.0     0.0  333.046312   0.0   
11       0  12700   61840.0   73541.0   1.0    0.0     0.0  157.892447   2.0   
12       0  20900   71972.0  101745.0   6.0    0.0     0.0   67.324562   6.0   
13       0  33700   73877.0  124834.0  10.0    0.0     0.0   68.482695   0.0   
14       0  16100   76981.0  106014.0   0.0    0.0     0.0  269.342629   1.0   
15       0   9000   56930.0   67557.0   0.0    0.0     1.0  118.699516   2.0   
16       0  25600  140649.0  212089.0   4.0    0.0     0.0  187.871421   0.0   
17       0  12000   98428.0  114820.0  16.0    0.0     1.0  188.148208   2.0   
18       0  87500   55938.0   86794.0  15.0    0.0     0.0  223.881040   0.0   
19       0   8400   60995.0   78444.0   4.0    0.0     1.0  123.738517   0.0   

    CLNO    DEBTINC  
0   27.0  29.209023  
1   14.0  31.545694  
2   15.0  41.210012  
3   12.0  28.602076  
4   13.0  30.686106  
5   16.0  34.368651  
6   21.0  41.418353  
7   10.0  23.040945  
8   26.0  27.007872  
9   21.0  36.910482  
10  20.0  39.294721  
11  35.0  41.651692  
12  23.0  38.513256  
13  34.0  25.960455  
14  21.0  39.799112  
15  18.0  36.686882  
16  29.0  40.033219  
17  15.0  36.737721  
18  16.0  36.753653  
19  23.0  26.932708

## Ejercicio 1: División de datos en conjuntos de entrenamiento y evaluación

La primer tarea consiste en dividir el conjunto de datos cargados en el apartado anterior en conjuntos de entrenamiento (o *training*) y evaluación (o *test*).

El primero será utilizado para la creación/selección del modelo de clasificación. El segundo se utilizará sólo al final (una vez elegidos los mejores hiperparámetros) para ver cuál es el resultado final del modelo sobre un conjunto de datos independiente.

In [4]:
# TODO: Dividir en datos de entrenamiento y evaluación
# Splitting the dataset into the Training set and the Test set

from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.25, random_state = 0)

/Users/EmanuelVFerrero/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Procesamiento de los datos por feature scaling

In [7]:
# Feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [8]:
X_test

array([[-1.37528222, -0.56224591, -0.87438886, ..., -0.68159539,
        -0.30546056, -1.47917542],
       [ 0.0327437 , -0.55495684, -0.55962845, ...,  1.11616096,
         0.5386551 ,  0.1531358 ],
       [-0.55471083,  0.05344322, -0.01753014, ..., -0.68159539,
         0.43314064, -0.9980157 ],
       ...,
       [-1.2354121 , -1.06448003, -1.28717767, ...,  5.31092577,
        -1.67714851, -0.52658562],
       [-0.23767188, -0.22405898, -0.3935829 , ..., -0.68159539,
        -0.83303285, -0.78534598],
       [-0.74120432, -0.65115961, -0.83822512, ..., -0.08234328,
        -0.09443164, -0.5122958 ]])

In [10]:
# Fitting logistic regression to the training test
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p =2)
classifier.fit(X_train, y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

Vamos a predecir algo.

In [11]:
# Prediciting the Test set results
y_pred = classifier.predict(X_test)

In [12]:
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Aplicamos matriz de confusión.

In [14]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [15]:
cm


array([[386,   9],
       [ 44,  25]])

Visualizamos los clusters del Training Set

In [18]:
y

0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
1824    1
1825    1
1826    1
1827    1
1828    1
1829    1
1830    1
1831    1
1832    1
1833    1
1834    1
1835    1
1836    1
1837    1
1838    1
1839    1
1840    1
1841    1
1842    1
1843    1
1844    1
1845    1
1846    1
1847    1
1848    1
1849    1
1850    1
1851    1
1852    1
1853    1
Name: TARGET, Length: 1854, dtype: int64

## Ejercicio 2: Elección de un modelo

Basándose en lo visto en el teórico escojan y justifiquen un modelo de aprendizaje automático. Recuerden que los pasos para elegir un modelo son:

### Selección de hipótesis

*TODO*

### Selección de regularizador

*TODO*

### Selección de función de coste

*TODO*

### Justificación de las selecciones

*TODO*

## Ejercicio 3: Selección de hiperparámetros

Utilizando búsqueda exhaustiva (*grid search*) con *5-fold cross-validation* y utilizando como métrica el área bajo la curva de ROC (o *ROC-AUC*), hagan una selección de los mejores hiperparámetros para su conjunto de datos y el modelo que hayan elegido en el apartado anterior.

In [ ]:
# TODO: Selección de hiperparámetros

## Ejercicio 4: Métricas sobre el conjunto de evaluación

Una vez encontrados los mejores hiperparámetros para el modelo seleccionado en los apartados anteriores se evalúa el modelo final entrenado sobre el conjunto de datos de evaluación seleccionado en el ejercicio 1. Pueden utilizar las métricas que crean convenientes. Es mejor utilizar más de una métrica. Particularmente el *reporte de clasificación* y la *matriz de confusión* son buenos ejemplos de métricas.

In [ ]:
# TODO: Evaluación del modelo

## Ejercicio 5 (opcional): Curvas de ROC

Como ejercicio adicional (opcional), pueden redefinir el umbral de decisión óptimo del problema a partir de los resultados que muestren curvas de ROC como justificación. 

Pueden ver esto mediante la [graficación de las curvas de ROC](http://scikit-learn.org/stable/auto_examples/model_selection/plot_roc.html). En el link que se les brinda se muestra como hacer para graficar curvas de ROC para problemas multiclase. Sin embargo se puede adaptar fácilmente a un problema binario obviando la parte donde se calcula la curva clase por clase.

In [ ]:
# TODO: Redefinir umbral de clasificación a través de los resultados vistos por graficar curvas de ROC